### ISSUE TITLE
Não consegui rodar o projeto!

### ISSUE THREAD

**Issue by danvitoriano** [cazanchetta/telegrambot#1]
Rapazes, infelizmente não consegui rodar o projeto de vocês! 😢 
Ao executar o Main, recebo esta mensagem:

```
Exception in thread "main" java.lang.NullPointerException
	at com.fiap.javaplatform.telegrambot.Main.main(Main.java:38)
```

Recomendo verificarem se acontece este erro e consertar algumas coisas:
- [x] adicionar um README no Github. Não sabemos como instalar o programa, nem como usar o Telegram Bot!
- [x] Vocês não geraram nenhuma documentação com Javadoc!
- [x] Atualizar a versão do Java que vocês estão usando no .classpath para ao menos a 8 (Java 1.8). A Java 1.5 é muito antiga!

Fico no aguardo que subam as alterações aqui no Github e me respondam na Issue para que eu possa baixar e testar novamente.

**Comment by cazanchetta** [comment]
Olá professor, fiz os ajustes solicitados, porém o sistema já estava rodando sem erro.

**Comment by danvitoriano** [comment]
Agora funcionou! O Javadoc está ok! Expliquem no README como rodar o programa ou os comandos do Maven para quem não souber como faz! Parabéns!
